version: 1.2
workflows:
  - name: myco_sra
    subclass: WDL
    primaryDescriptorPath: /myco_sra.wdl
    readMePath: /doc/myco_sra.md
    testParameterFiles:
      - /inputs/myco_sra_terra.json
      - /inputs/myco_sra_local.json
    authors:
      - orcid: 0000-0003-4896-1858
